# Dev 分支推送部署预览
## 仅部署 Win 端
name: Build Home

on:
  push:
    branches:
      - master

jobs:
  release:
    name: Build Website
    runs-on: ubuntu-latest

    steps:
      # 检出 Git 仓库
      - name: Check out git repository
        uses: actions/checkout@v4.1.1
      # 安装 Node.js
      - name: Install Node.js
        uses: actions/setup-node@v4.0.0
        with:
          node-version: "18.x"
      # 复制环境变量文件
      # - name: Copy .env.example
        # run: |
        #   cp .env.example .env
        #   # if (-not (Test-Path .env)) {
        #   #   Copy-Item .env.example .env
        #   # } else {
        #   #   Write-Host ".env file already exists. Skipping the copy step."
        #   # }
      # 安装项目依赖
      - name: Install Dependencies
        run: npm install
      # 构建程序
      - name: Build Website
        run: npm run build
        env:
          GITHUB_TOKEN: ${{ secrets.GH_HOME_ACTION_TOKEN }}
      # 上传构建产物
      # - name: Upload artifacts
      #   uses: actions/upload-artifact@v3.1.3
      #   with:
      #     name: Home
      #     path: dist
      # 部署到 GitHub Pages
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_HOME_ACTION_TOKEN }}
          publish_dir: ./dist
          commit_message: ${{ github.event.head_commit.message }}
